In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
myarr = np.array(mylist)

In [4]:
type(mylist)

list

In [5]:
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))  # rows and columns in a tuple as intput

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
len(np.linspace(0,5,21))

21

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(1)

array([0.20171013])

In [23]:
np.random.rand(5,2)

array([[0.13530969, 0.43049016],
       [0.9268222 , 0.74765939],
       [0.65533313, 0.06106769],
       [0.65767675, 0.1526595 ],
       [0.07595738, 0.94684958]])

In [24]:
np.random.randn(10)

array([ 0.90372986, -0.02183721, -0.19943224, -0.85214369,  1.16905989,
        0.4816186 ,  0.2911899 , -0.99140106,  0.44181218,  0.13738009])

In [25]:
np.random.randn(2,3)

array([[-1.25670882,  0.70995348,  0.16628559],
       [-0.67033508, -0.88458525,  1.10449849]])

In [26]:
np.random.randint(0,101,5)

array([37, 45, 83, 10, 42])

In [27]:
np.random.randint(0,101,(4,5))

array([[ 30,  99,  50,  56,  35],
       [ 50,  81,  50,  75,  59],
       [ 13,  22,  55,  69,  18],
       [ 97,  49,  77,   2, 100]])

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
arr = np.arange(0,25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr = np.random.randint(0,101,10)

In [33]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [34]:
ranarr.max()

99

In [35]:
ranarr.min()

2

In [36]:
ranarr.argmax()

5

In [37]:
ranarr.argmin()

7

In [38]:
ranarr.dtype

dtype('int32')

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(5, 5)

In [44]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])