In [1]:
import numpy as np

In [4]:
arr = np.arange(1,11)

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[7]

8

In [7]:
arr[1:5]

array([2, 3, 4, 5])

In [8]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [9]:
arr[:5]

array([1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [14]:
arr  = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:5]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d.shape

(3, 3)

In [27]:
arr_2d[0] #row selection

array([ 5, 10, 15])

In [28]:
arr_2d[2]

array([35, 40, 45])

In [29]:
arr_2d[1][1]

25

In [30]:
arr_2d[1,1]

25

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr = np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr>4

In [36]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])